name: sac

agent_name: ${now:%Y%m%d}_sac_gnn  # Agent name for training or evaluation (default: today's date + '_sac_gnn')

cplexpath: "/opt/opl/bin/x86-64_linux/"  # Defines directory of the CPLEX installation
  
directory: "saved_files"  # Defines directory where to save files

max_episodes: 10000  # Number of episodes to train agent (default: 16k)

no_cuda: false  # Disables CUDA training

batch_size: 100  # Defines batch size

p_lr: 1e-3  # Define policy learning rate

q_lr: 1e-3  # Defines q-value learning rate

alpha: 0.3  # Defines entropy coefficient

auto_entropy: false  # Use automatic entropy tuning

hidden_size: 256  # Defines hidden units in the MLP layers

clip: 500  # Clip value for gradient clipping (default: 500)

checkpoint_path: "SAC"  # Path where to save model checkpoints
  
rew_scale: 0.01  # Defines reward scale

use_LSTM: false  # Use LSTM in the model

input_size: 13 # Number of node features

test_episodes: 10 # Number of episodes to test agent

determinisitc_backup: False #use q-value deterministic backup

pretrained_path: null 

only_q_steps: 0 